### ISSUE TITLE
License Information Is Missing

### ISSUE THREAD

**Issue by chrisv1351** [TheOdooStore/AppManager#1]
Under which license app_manager module is.

**Comment by Yenthe666** [comment]
Done in https://github.com/TheOdooStore/AppManager/commit/63d914a2a67dd3ad34595d4b8aa29dc7a0eb1e96 and https://github.com/TheOdooStore/AppManager/commit/f6f50c132482506e7e97e514b5ccc4dae455603e :) 
It's `LGPL-3`
